### ISSUE TITLE
[Show]: NMB48 5th & 6th Anniversary LIVE

### ISSUE THREAD

**Issue by tjs310** [Onlookers-Group/TexonEmby#10]
### 您想看综艺的名字/译名？

NMB48 5th & 6th Anniversary LIVE

### 这部综艺的上映时间？

2017-10-11

### 这部综艺的TMDB链接？

-

### 这部综艺的国家？

Japan

**Comment by futurkk** [comment]
除了这个5th没找到 其他应该都找到了
有些清晰度有点一般，等等我会传进去。
其他issue先关闭了

**Comment by tjs310** [comment]
> 除了这个5th没找到 其他应该都找到了 有些清晰度有点一般，等等我会传进去。 其他issue先关闭了
简直是神一般的速度，太强了。清晰度一般也没关系有更好画质的时候再更新咯，万分感谢！容我继续发帖求片^^

**Comment by futurkk** [comment]
不过我也不知道我找的对不对。。
说实话如果tmdb没有的话，我只能看这个日文像不像

**Comment by tjs310** [comment]
>

> 不过我也不知道我找的对不对。。 说实话如果tmdb没有的话，我只能看这个日文像不像

已经十分感激的了。TMDB应该是没有的都是演唱会。电影的话可能就能对应找到。
