### ISSUE TITLE
[Movie]: トリック　劇場版

### ISSUE THREAD

**Issue by tjs310** [Onlookers-Group/TexonEmby#14]
### 您想看电影的名字/译名？

圈套剧场版

### 这部电影的上映时间？

2002-11-07

### 这部电影的TMDB链接？

https://www.themoviedb.org/movie/72092-trick-the-movie

### 这部电影的国家？

Japan

**Comment by futurkk** [comment]
圈套剧场版4部再上传了。传好后等扫库就行。

**Comment by tjs310** [comment]
> 圈套剧场版4部再上传了。传好后等扫库就行。

收到～感谢，另，李克勤30周年演唱会播放不能哦。

**Comment by tjs310** [comment]
> 晚点看看， 这个有上下半场，我要研究下怎么命名。。

是的 蓝光是2张BD
