### ISSUE TITLE
[Show]: DIR EN GREY THE FINAL DAYS OF STUDIO COAST 2022

### ISSUE THREAD

**Issue by tjs310** [Onlookers-Group/TexonEmby#15]
### 您想看综艺的名字/译名？

DIR EN GREY THE FINAL DAYS OF STUDIO COAST 2022

### 这部综艺的上映时间？

2022-9-14

### 这部综艺的TMDB链接？

-

### 这部综艺的国家？

Japan

**Comment by futurkk** [comment]
在传了。不过这种演唱会 我不知道哪里有带元数据的版本，可能刮削后是奇怪的名字。

**Comment by tjs310** [comment]
> 在传了。不过这种演唱会 我不知道哪里有带元数据的版本，可能刮削后是奇怪的名字。

没关系 有就有 没有也不强求呢，谢谢。
