### ISSUE TITLE
[Series]: 

### ISSUE THREAD

**Issue by yingjun-aka** [Onlookers-Group/TexonEmby#18]
### 您想看剧集的名字/译名？

法证先锋1−5

### 这部剧集的上映时间？

2006年

### 这部剧集的TMDB链接？

https://www.themoviedb.org/tv/4114-forensic-heroes

### 这部剧集的国家？

China/Hong Kong/Macao/Taiwan

**Comment by futurkk** [comment]
这部剧是有的

**Comment by yingjun-aka** [comment]
好的，谢谢哈，名字打错没搜到
