### ISSUE TITLE
[Show]: 

### ISSUE THREAD

**Issue by yingjun-aka** [Onlookers-Group/TexonEmby#19]
### 您想看综艺的名字/译名？

乐队的夏天（1-2季）

### 这部综艺的上映时间？

2019

### 这部综艺的TMDB链接？

https://www.themoviedb.org/tv/90756

### 这部综艺的国家？

China/Hong Kong/Macao/Taiwan

**Comment by futurkk** [comment]
上了。等今晚17:00会扫库。
