### ISSUE TITLE
[Series]: 

### ISSUE THREAD

**Issue by guiqulaixiovo** [Onlookers-Group/TexonEmby#20]
### 您想看剧集的名字/译名？

非自然死亡

### 这部剧集的上映时间？

2018

### 这部剧集的TMDB链接？

https://www.themoviedb.org/tv/75701

### 这部剧集的国家？

Japan

**Comment by futurkk** [comment]
上了。

**Comment by futurkk** [comment]
重新上了。等今晚17:00会扫库。
