### ISSUE TITLE
[Anime]: 《莉可丽丝》求更新哇，emby只有5集，已经出到13集了呃。

### ISSUE THREAD

**Issue by LevineWoo** [Onlookers-Group/TexonEmby#21]
### 您想看动漫的名字/译名？

莉可丽丝

### 这部动漫的上映时间？

2022

### 这部动漫的TMDB链接？

https://www.themoviedb.org/tv/154494

### 这部动漫的国家？

Japan

**Comment by JunSAMA233** [comment]
![Screenshot_2022-11-06-04-13-18-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/78623580/200139208-cb9d7efd-42bd-4938-a786-ee478aa324c0.jpg)

**Comment by JunSAMA233** [comment]
![IMG_20221106_041739](https://user-images.githubusercontent.com/78623580/200139272-efa94d68-4abe-479c-ab02-58f267fa47c0.jpg)


Are u sure?
