### ISSUE TITLE
[Movie]

### ISSUE THREAD

**Issue by hanos116** [Onlookers-Group/TexonEmby#22]
**您想看电影的名字/译名？**

蓝风筝 Blue kite

**这部剧集的上映时间？**

1993

**这部剧集的TMDB链接？**

https://www.imdb.com/title/tt0107358/

**这部剧集的国家？**

China

**Comment by futurkk** [comment]
请按照规定模板建立issue。

**Comment by hanos116** [comment]
1> 请按照规定模板建立issue。

**Comment by hanos116** [comment]
已更正

**Comment by futurkk** [comment]
上了。等今晚17:00会扫库。
