### ISSUE TITLE
[Series]: 親愛なる僕へ殺意をこめて

### ISSUE THREAD

**Issue by tjs310** [Onlookers-Group/TexonEmby#24]
### 您想看剧集的名字/译名？

为亲爱的我致上杀意

### 这部剧集的上映时间？

2022-10-05

### 这部剧集的TMDB链接？

https://www.themoviedb.org/tv/210085

### 这部剧集的国家？

Japan

**Comment by futurkk** [comment]
这部9号更新完看看。目前没有太好的字幕

**Comment by tjs310** [comment]
> 这部9号更新完看看。目前没有太好的字幕

谢谢，日语类的片如果可以中日字幕同时就好了。

**Comment by tjs310** [comment]
这个好像还没更新哦

**Comment by futurkk** [comment]
我只找到了生肉..就还没上

**Comment by tjs310** [comment]
> 我只找到了生肉..就还没上

哦哦没关系，感谢啦。

**Comment by futurkk** [comment]
上了
